name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit SHA for the provided version
        id: get-sha
        run: |
          # Fetch the SHA for the provided version tag
          SHA=$(git rev-list -n 1 ${{ github.event.inputs.version }})
          echo "::set-output name=sha::$SHA"
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          version: ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease }}
          commitish: ${{ steps.get-sha.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}